### ISSUE TITLE
class options

### ISSUE THREAD

**Issue by williamengbjerg** [benface/tailwindcss-animations#1]
Can you list all the class options?

**Comment by benface** [comment]
Hey @williamengbjerg, I'm not exactly sure what you mean? In the [Usage](https://github.com/benface/tailwindcss-animations#usage) section of the README, if you scroll down a bit, you will see the generated CSS for an example config. I admit it's not the easiest thing to read, but you can see how the utility classes are named:

- `animation-[name]` (`animation-none`, `animation-spin`, `animation-jump`, etc.)
- `animation-[duration]` (`animation-0s`, `animation-1s`, etc.)
- `animation-[timing-function]` (`animation-linear`, `animation-ease`, etc.)
- `animation-delay-[delay]` (`animation-delay-0s`, `animation-delay-1s`, etc.)
- `animation-[iteration-count]` (`animation-once`, `animation-infinite`, etc.)
- `animation-[direction]` (`animation-normal`, `animation-reverse`, etc.)
- `animation-fill-[fill-mode]` (`animation-fill-none`, `animation-fill-forwards`, etc.)
- `animation-[play-state]` (`animation-running` and `animation-paused`, not configurable)

Does that help, or did you mean something else?

**Comment by williamengbjerg** [comment]
Thank's for the examples. That's what I meant:)
