### ISSUE TITLE
Can't extend some options

### ISSUE THREAD

**Issue by cappslock** [benface/tailwindcss-animations#2]
This is useful, thanks for creating it.

Found a small bug. I have a config like this:

```
// See https://tailwindcss.com/docs/configuration for details

module.exports = {
  theme: {
    extend: {
      animations: {
        spin: {
          from: {
            transform: "rotate(0deg)"
          },
          to: {
            transform: "rotate(360deg)"
          }
        }
      },
      animationDuration: {
        "10s": "10s"
      },
      fontFamily: {
        default: ["Courier", "monospace"]
      }
    }
  },
  variants: {},
  plugins: [
    require("tailwindcss-transitions")(),
    require("tailwindcss-animations")()
  ]
};
```

Specifying that 10s duration removes the other duration keys (so `animation-2s` for example won't work). However, because it's within the `extend` key, this should merge with the defaults.

**Comment by benface** [comment]
Hey @cappslock this is a [known issue](https://github.com/benface/tailwindcss-transitions/issues/8#issuecomment-532481619) affecting all Tailwind plugins, but the good news is that [a fix is coming in Tailwind 1.2](https://github.com/tailwindcss/tailwindcss/pull/1162) which I believe should be out soon, after which I'll release [v2.0 of this plugin](https://github.com/benface/tailwindcss-animations/blob/next/CHANGELOG.md) to support the new feature that negates this issue.
